export const Listofvarities = []
export const listarray = [
  {
    productName: "Cadbury Dairy Milk Silk Chocolate Bar, 150 g",
    productWeight: 150,
    weightUnit: 'g',
    productPrice: 50,
    productMRP: 150,
    marketRating: 4,


  },
  {
    productName: "Cadbury Dairy Milk Silk Chocolate Bar, 150 g",
    productWeight: 150,
    weightUnit: 'g',
    productPrice: 50,
    productMRP: 150,
    marketRating: 4,


  },
  {
    productName: "Cadbury Dairy Milk Silk Chocolate Bar, 150 g",
    productWeight: 150,
    weightUnit: 'g',
    productPrice: 50,
    productMRP: 150,
    marketRating: 4,


  },
  {
    productName: "Cadbury Dairy Milk Silk Chocolate Bar, 150 g",
    productWeight: 150,
    weightUnit: 'g',
    productPrice: 50,
    productMRP: 150,
    marketRating: 4,


  },
  {
    productName: "Cadbury Dairy Milk Silk Chocolate Bar, 150 g",
    productWeight: 150,
    weightUnit: 'g',
    productPrice: 50,
    productMRP: 150,
    marketRating: 4,


  },
  {
    productName: "Cadbury Dairy Milk Silk Chocolate Bar, 150 g",
    productWeight: 150,
    weightUnit: 'g',
    productPrice: 50,
    productMRP: 150,
    marketRating: 4,


  },
]

export const SpecialOfferList = [

]


export const CategorieLists = [
  {
    id: 1,
    name: "Electronics",
    subcategories: [
      { id: 101, name: "Mobile Phones" },
      { id: 102, name: "Laptops" },
      { id: 103, name: "Tablets" },
      { id: 104, name: "Cameras" }
    ]
  },
  {
    id: 2,
    name: "Fashion",
    subcategories: [
      { id: 201, name: "Men's Clothing" },
      { id: 202, name: "Women's Clothing" },
      { id: 203, name: "Accessories" },
      { id: 204, name: "Shoes" }
    ]
  },
  {
    id: 3,
    name: "Home & Kitchen",
    subcategories: [
      { id: 301, name: "Furniture" },
      { id: 302, name: "Appliances" },
      { id: 303, name: "Decor" },
      { id: 304, name: "Cookware" }
    ]
  },
  {
    id: 4,
    name: "Sports & Outdoors",
    subcategories: [
      { id: 401, name: "Exercise Equipment" },
      { id: 402, name: "Outdoor Gear" },
      { id: 403, name: "Sportswear" },
      { id: 404, name: "Footwear" }
    ]
  },
  {
    id: 5,
    name: "Beauty & Health",
    subcategories: [
      { id: 501, name: "Makeup" },
      { id: 502, name: "Skincare" },
      { id: 503, name: "Hair Care" },
      { id: 504, name: "Wellness" }
    ]
  },
  {
    id: 6,
    name: "Toys & Baby",
    subcategories: [
      { id: 601, name: "Toys" },
      { id: 602, name: "Baby Gear" },
      { id: 603, name: "Nursery" },
      { id: 604, name: "Educational Toys" }
    ]
  }
];



export const ProductArray = [
  {
    id: 1,
    name: "Wireless Noise-Canceling Headphones",
    category: "Electronics",
    brand: "AudioPro",
    description: "Premium over-ear wireless headphones with active noise cancellation and 30-hour battery life.",
    price: 199.99,
    discountPrice: 149.99,
    currency: "USD",
    availability: "In Stock",
    colorOptions: ["Black", "Silver", "Blue"],
    sizeOptions: ["One Size"],
    dimensions: { width: "6.5 inches", height: "7.8 inches", depth: "3.2 inches" },
    weight: "0.85 lbs",
    material: "Plastic and Leather",
    features: ["Bluetooth 5.0", "Built-in microphone", "Foldable design", "Fast charging (10 min = 5 hours)"],
    technicalSpecifications: {
      noiseCancellation: "Active",
      batteryLife: "30 hours",
      connectivity: "Bluetooth 5.0 / 3.5mm AUX",
    },
    images: ["https://example.com/images/headphones1.jpg", "https://example.com/images/headphones2.jpg"],
    videos: ["https://example.com/videos/headphones-review.mp4"],
    rating: 4.5,
    reviewCount: 127,
    customerReviews: [{ reviewerName: "John Doe", rating: 5, comment: "Great quality!" }],
    originalPrice: 199.99,
    discountPercentage: 25,
    taxInfo: "Price includes 10% VAT",
    shippingCost: "Free",
    bundleOffers: "Buy 2, get 10% off",
  },
  {
    id: 2,
    name: "Stainless Steel Water Bottle (32 oz)",
    category: "Home & Kitchen",
    brand: "EcoHydro",
    description: "Double-walled, vacuum-insulated water bottle to keep beverages cold for 24 hours or hot for 12 hours.",
    price: 24.99,
    discountPrice: null,
    currency: "USD",
    availability: "In Stock",
    colorOptions: ["Silver", "Blue", "Red"],
    sizeOptions: ["32 oz"],
    dimensions: { width: "3.5 inches", height: "10.5 inches" },
    weight: "0.65 lbs",
    material: "Stainless Steel",
    features: ["Leakproof lid", "BPA-free", "Eco-friendly"],
    technicalSpecifications: { insulation: "Vacuum-insulated", capacity: "32 oz" },
    images: ["https://example.com/images/waterbottle1.jpg"],
    videos: [],
    rating: 4.7,
    reviewCount: 89,
    customerReviews: [{ reviewerName: "Alice Green", rating: 5, comment: "Keeps my drinks cold!" }],
    originalPrice: 24.99,
    discountPercentage: null,
    taxInfo: "Price includes 8% VAT",
    shippingCost: "$5",
    bundleOffers: "Buy 3, get 1 free",
  },
  {
    id: 3,
    name: "Men’s Running Shoes",
    category: "Footwear",
    brand: "RunMax",
    description: "Lightweight, breathable running shoes with cushioned soles for comfort.",
    price: 89.99,
    discountPrice: 74.99,
    currency: "USD",
    availability: "Limited Stock",
    colorOptions: ["Black", "Gray"],
    sizeOptions: [7, 8, 9, 10, 11],
    weight: "1.2 lbs",
    material: "Mesh and Rubber",
    features: ["Anti-slip sole", "Breathable material"],
    technicalSpecifications: { soleType: "Cushioned", archSupport: "Medium" },
    images: ["https://example.com/images/shoes1.jpg"],
    videos: ["https://example.com/videos/shoes-demo.mp4"],
    rating: 4.4,
    reviewCount: 220,
    customerReviews: [{ reviewerName: "Michael Brown", rating: 4, comment: "Good for running." }],
    originalPrice: 89.99,
    discountPercentage: 17,
    taxInfo: "Price includes 5% VAT",
    shippingCost: "Free above $50",
    bundleOffers: null,
  },
  {
    id: 4,
    name: "Smart LED Desk Lamp",
    category: "Home Office",
    brand: "BrightHome",
    description: "Adjustable LED desk lamp with touch controls, 3 brightness levels, and a USB charging port.",
    price: 49.99,
    discountPrice: 39.99,
    currency: "USD",
    availability: "In Stock",
    colorOptions: ["White", "Black"],
    sizeOptions: ["One Size"],
    dimensions: { width: "5 inches", height: "15 inches" },
    weight: "2.1 lbs",
    material: "Aluminum",
    features: ["Energy-efficient", "Adjustable arm", "USB charging port"],
    technicalSpecifications: { brightnessLevels: 3, powerSource: "USB-powered" },
    images: ["https://example.com/images/desk-lamp1.jpg"],
    videos: [],
    rating: 4.6,
    reviewCount: 65,
    customerReviews: [{ reviewerName: "Sarah Lee", rating: 5, comment: "Perfect for my study table." }],
    originalPrice: 49.99,
    discountPercentage: 20,
    taxInfo: "Price includes 5% VAT",
    shippingCost: "$10",
    bundleOffers: null,
  },
  {
    id: 5,
    name: "Organic Cotton T-Shirt",
    category: "Clothing",
    brand: "EcoWear",
    description: "Soft and breathable t-shirt made from 100% organic cotton. Perfect for casual wear.",
    price: 19.99,
    discountPrice: null,
    currency: "USD",
    availability: "In Stock",
    colorOptions: ["White", "Black", "Gray"],
    sizeOptions: ["S", "M", "L", "XL"],
    weight: "0.2 lbs",
    material: "Organic Cotton",
    features: ["Eco-friendly", "Soft fabric"],
    technicalSpecifications: null,
    images: ["https://example.com/images/tshirt1.jpg"],
    videos: [],
    rating: 4.8,
    reviewCount: 75,
    customerReviews: [{ reviewerName: "Emily Rose", rating: 5, comment: "Super comfortable!" }],
    originalPrice: 19.99,
    discountPercentage: null,
    taxInfo: "Tax included",
    shippingCost: "Free",
    bundleOffers: "Buy 2, get 1 free",
  },
  {
    id: 6,
    name: "Bluetooth Portable Speaker",
    category: "Electronics",
    brand: "SoundPro",
    description: "Compact portable speaker with deep bass and 12-hour battery life. Water-resistant for outdoor use.",
    price: 59.99,
    discountPrice: 49.99,
    currency: "USD",
    availability: "In Stock",
    colorOptions: ["Red", "Black"],
    sizeOptions: ["One Size"],
    weight: "1.1 lbs",
    material: "Plastic",
    features: ["Bluetooth 5.1", "Water-resistant"],
    technicalSpecifications: { batteryLife: "12 hours", connectivity: "Bluetooth 5.1" },
    images: ["https://example.com/images/speaker1.jpg"],
    videos: ["https://example.com/videos/speaker-demo.mp4"],
    rating: 4.5,
    reviewCount: 150,
    customerReviews: [{ reviewerName: "Tom Hanks", rating: 5, comment: "Amazing sound quality!" }],
    originalPrice: 59.99,
    discountPercentage: 17,
    taxInfo: "Tax included",
    shippingCost: "Free",
    bundleOffers: null,
  },
  {
    id: 7,
    name: "Ceramic Nonstick Frying Pan (12-inch)",
    category: "Home & Kitchen",
    brand: "KitchenPro",
    description: "Durable nonstick frying pan with ceramic coating for healthier cooking and easy cleaning.",
    price: 34.99,
    discountPrice: null,
    currency: "USD",
    availability: "In Stock",
    colorOptions: ["Gray", "Black"],
    sizeOptions: ["12-inch"],
    weight: "2.5 lbs",
    material: "Ceramic-coated Aluminum",
    features: ["Nonstick", "Oven-safe"],
    technicalSpecifications: { heatResistance: "Up to 450°F" },
    images: ["https://example.com/images/frying-pan1.jpg"],
    videos: [],
    rating: 4.3,
    reviewCount: 85,
    customerReviews: [{ reviewerName: "Laura White", rating: 4, comment: "Good quality for the price." }],
    originalPrice: 34.99,
    discountPercentage: null,
    taxInfo: "Tax included",
    shippingCost: "$5",
    bundleOffers: null,
  },
  {
    id: 8,
    name: "Fitness Tracker Smartwatch",
    category: "Electronics",
    brand: "FitPro",
    description: "Track your fitness goals with this smartwatch, featuring heart rate monitoring, sleep tracking, and step counting.",
    price: 79.99,
    discountPrice: 69.99,
    currency: "USD",
    availability: "In Stock",
    colorOptions: ["Black", "Pink", "Blue"],
    sizeOptions: ["Adjustable"],
    weight: "0.3 lbs",
    material: "Silicone and Plastic",
    features: ["Heart rate monitor", "Step counter", "Water-resistant"],
    technicalSpecifications: { batteryLife: "7 days", compatibility: "iOS and Android" },
    images: ["https://example.com/images/smartwatch1.jpg"],
    videos: ["https://example.com/videos/smartwatch-demo.mp4"],
    rating: 4.6,
    reviewCount: 300,
    customerReviews: [{ reviewerName: "Anna Green", rating: 5, comment: "Perfect for workouts!" }],
    originalPrice: 79.99,
    discountPercentage: 12,
    taxInfo: "Tax included",
    shippingCost: "Free",
    bundleOffers: "Get extra straps for $10",
  },
  {
    id: 9,
    name: "Wireless Keyboard and Mouse Combo",
    category: "Electronics",
    brand: "KeyTech",
    description: "Ergonomic wireless keyboard and mouse combo with long battery life.",
    price: 49.99,
    discountPrice: 39.99,
    currency: "USD",
    availability: "In Stock",
    colorOptions: ["Black", "White"],
    sizeOptions: ["One Size"],
    weight: "1.5 lbs",
    material: "Plastic",
    features: ["2.4GHz wireless connectivity", "Ergonomic design"],
    technicalSpecifications: { range: "33 feet", batteryLife: "6 months" },
    images: ["https://example.com/images/keyboard-mouse1.jpg"],
    videos: [],
    rating: 4.5,
    reviewCount: 110,
    customerReviews: [{ reviewerName: "David Smith", rating: 4, comment: "Great value for money." }],
    originalPrice: 49.99,
    discountPercentage: 20,
    taxInfo: "Tax included",
    shippingCost: "$5",
    bundleOffers: null,
  },
  {
    id: 10,
    name: "4K Ultra HD Smart TV (55-inch)",
    category: "Electronics",
    brand: "VisionMax",
    description: "Experience stunning visuals with this 4K Ultra HD Smart TV featuring HDR and streaming apps.",
    price: 499.99,
    discountPrice: 399.99,
    currency: "USD",
    availability: "In Stock",
    colorOptions: ["Black"],
    sizeOptions: ["55-inch"],
    weight: "32 lbs",
    material: "Plastic and Metal",
    features: ["4K Ultra HD resolution", "HDR support", "Smart apps"],
    technicalSpecifications: { resolution: "3840x2160", refreshRate: "60Hz" },
    images: ["https://example.com/images/tv1.jpg"],
    videos: ["https://example.com/videos/tv-demo.mp4"],
    rating: 4.8,
    reviewCount: 450,
    customerReviews: [{ reviewerName: "Chris Taylor", rating: 5, comment: "Amazing picture quality!" }],
    originalPrice: 499.99,
    discountPercentage: 20,
    taxInfo: "Tax included",
    shippingCost: "Free",
    bundleOffers: "Free wall mount included",
  },
];
